### select
GET http://localhost:1323/select HTTP/1.1

### selectWithPaging
POST http://localhost:1323/paging HTTP/1.1
content-type: application/json

{
    "limit": 4,
    "offset": 1
}

### selectWithPageNum
POST http://localhost:1323/pagenum HTTP/1.1
content-type: application/json

{
    "page": 4
}

### insert
POST http://localhost:1323/insert HTTP/1.1
content-type: application/json

{
    "P_Name": "Bart",
    "P_Email": "bart@abc.com"
}

### update
PUT http://localhost:1323/update HTTP/1.1
content-type: application/json

{
    "P_Name": "Homer",
    "P_Email": "homer@abc.com",
    "P_Idx": 14
}

### delete
DELETE http://localhost:1323/delete HTTP/1.1
content-type: application/json

{
    "P_Idx": 13
}

### Accessible
GET http://localhost:1323/ HTTP/1.1

### Login
POST http://localhost:1323/login
Content-Type: application/json

{
    "J_Name": "Joe",
    "J_Email": "joe@abc.com"
}

### Restricted
GET http://localhost:1323/restricted HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJKX0lkeCI6MSwiSl9OYW1lIjoiSm9lIiwiSl9FbWFpbCI6ImpvZUBhYmMuY29tIiwiZXhwIjoxNjEzNzA2NzQzfQ.Y404KYAHFZ6qNv8O0-43ADODwyk0gO90lbRxyx4VyIk


###

GET https://example.com/comments/1 HTTP/1.1

###

GET https://example.com/topics/1 HTTP/1.1

###

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
